#!/bin/bash

# 0    1 2 3 4                5
# nnet l h e <train-set-file> <test-set-file>

# 0      1   2     3    4    5      6
# net.py l/n train test rate epochs num_hidden

python net.py n $4 $5 $1 $3 $2
